# Generated by Django 4.2 on 2023-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_floor', models.PositiveIntegerField()),
                ('is_operational', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('is_moving', models.BooleanField(default=True)),
                ('direction', models.IntegerField()),
                ('door_opened', models.BooleanField(default=False)),
            ],
        ),
    ]
