# Generated by Django 4.2 on 2023-05-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='elevator',
            name='last_floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
    ]
