# Generated by Django 4.2 on 2023-05-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_apis', '0002_remove_elevator_is_selected_elevator_last_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elevator_current_floor', models.IntegerField(null=True)),
                ('target_floor', models.IntegerField(null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('elevator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator', to='elevator_apis.elevator')),
            ],
        ),
    ]
